[package]
name = "rust_server"
version = "0.1.0"
authors = ["Michael Andersson <michael.andersson@netlight.com>"]
edition = "2018"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
protobuf = "2.8.1"

[build-dependencies]
protoc-rust = "2.0"